
import Navbar from "@/components/Navbar";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css'
import { AuthProvider } from "@/context/AuthContext";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
